# Generated by Django 4.2.2 on 2023-06-30 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publication_year', models.DateTimeField(default=datetime.datetime(2023, 6, 30, 19, 13, 47, 482802), null=True)),
                ('page_numbers', models.IntegerField()),
                ('language', models.CharField(choices=[('english', 'English'), ('portuguese', 'Portuguese'), ('spenish', 'Spanish'), ('french', 'French'), ('italian', 'Italian'), ('german', 'German'), ('not informed', 'Notinformed')], default='not informed', max_length=50)),
                ('genre', models.CharField(max_length=255)),
                ('disponibility', models.BooleanField(default=True, null=True)),
                ('copies_number', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
