# Generated by Django 4.2.2 on 2023-07-03 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_user_book_users_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 10, 44, 26, 739416), null=True),
        ),
    ]
