# Generated by Django 4.2.2 on 2023-07-07 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_alter_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Portuguese', 'Portuguese'), ('Spanish', 'Spanish'), ('French', 'French'), ('Italian', 'Italian'), ('German', 'German'), ('Not Informed', 'Notinformed')], default='Not Informed', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 13, 39, 3, 735476), null=True),
        ),
    ]
