# Generated by Django 4.2.3 on 2023-07-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_alter_book_publication_year 2'),
        ('books', '0026_alter_book_publication_year'),
        ('books', '0026_alter_book_publication_year 2'),
    ]

    operations = [
    ]
