# Generated by Django 4.2.3 on 2023-07-07 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0027_merge_20230707_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 22, 32, 4, 917250), null=True),
        ),
    ]
