# Generated by Django 4.2.2 on 2023-07-05 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follower",
            old_name="book",
            new_name="book_followed",
        ),
        migrations.RenameField(
            model_name="follower",
            old_name="user",
            new_name="student",
        ),
    ]
