# Generated by Django 4.2.2 on 2023-07-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_rename_book_follower_book_followed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['id']},
        ),
    ]
