# Generated by Django 4.2.2 on 2023-06-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('loan_return', models.DateTimeField()),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy', to='copies.copy')),
            ],
        ),
    ]
