# Generated by Django 4.2.2 on 2023-06-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='copie',
            new_name='copy',
        ),
    ]
