# Generated by Django 4.2.2 on 2023-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='returned_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(),
        ),
    ]
