# Generated by Django 4.2.2 on 2023-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_is_active_loan_returned_at_alter_loan_loan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
