# Generated by Django 4.2.2 on 2023-07-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_loan_date_alter_loan_loan_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_return',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateField(null=True),
        ),
    ]
