# Generated by Django 4.2.2 on 2023-07-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loan_loan_date_alter_loan_loan_return_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['id']},
        ),
    ]
