# Generated by Django 4.2.2 on 2023-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0002_alter_copy_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='status_for_loan',
        ),
        migrations.AddField(
            model_name='copy',
            name='is_avaliable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
