# Generated by Django 4.2.2 on 2023-07-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0003_remove_copy_status_for_loan_copy_is_avaliable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copy',
            options={'ordering': ['id']},
        ),
    ]
